language: ruby
rvm:
 - 2.3.0
services:
- postgresql
before_script:
  - psql -c "CREATE USER andrecosta;CREATE DATABASE etikette_development;GRANT ALL PRIVILEGES ON DATABASE etikette_development to andrecosta" -U postgres
